### ISSUE TITLE
File plugin - add "source" parameter

### ISSUE THREAD

**Issue by spigell** [melezhik/file#1]
Could you add new parameter "source" for the plugin? "A source file, which will be copied into place on the local system." - like in puppet or other CM. Right now it is present in templayer plugin, but it will be good have it here. 
Thanks.
Using param "Content" for big files is not good idea(IMHO).

**Comment by melezhik** [comment]
@Spigell  приветствую! Может быть будем по русски задачи обсуждать, если вы не против?

**Comment by spigell** [comment]
Да, можем и так. На мой взгляд, в этот плагин надо добавить source. Я пробовал его просто вписать в sparrowfile в параметры вместо content, но не взлетело, да.(

**Comment by melezhik** [comment]
да, понял. не должно было взлететь, нужно source добавлять в сам плагин file.
Я правильно вас понимаю, что вы хотите `source` - путь к файлу, который будет скопирован в `target`?

Пример вызова:
```
# скопировать source в path :
file "/path/to/target", %( source  => '/path/to/source/' );
```

**Comment by spigell** [comment]
Да, описание верно. Я так понимаю, что вручную его можно будет вызывать через  `--param source=/path/to/source`, а также через sparrowDO? Если так, то как будет это работать, если вдруг я укажу и `content` и `source` в одном месте?

**Comment by melezhik** [comment]
> Если так, то как будет это работать, если вдруг я укажу и content и source в одном месте?

предлагаю, что если `content` задан, то `source` не учитывается.

**Comment by melezhik** [comment]
> Я так понимаю, что вручную его можно будет вызывать через --param source=/path/to/source, а также через sparrowDO?

как только обновлю плагин, то через sparrow будет доступно сразу ( как вы написали  `--param source=/path/to/source`) , а через sparrowdo можно так же будет использовать, но пока только через plugin dsl : 

```
task-run 'create my file', 'file', %(
  action      => 'create',
  target      => '/path/to/target',
  source     => '/path/to/source'
);
```

Для вызова через core-dsl ( как я написал в предыдущем коменте  ) -  нужно будет добавить новый параметр `source` - чуть позже

**Comment by spigell** [comment]
> предлагаю, что если content задан, то source не учитывается.

Паппет, к примеру, выдает ошибку на несовместимые параметры:
```
Error: Failed to apply catalog: Validation of File[/home/spigell/1.conf] failed: You cannot speci│
fy more than one of content, source, target at /etc/puppetlabs/code/environments/production/manif│
ests/nodes.pp:7
```
Может быть, тоже возвращать ошибку, если это не сложно. Или хотя бы предупреждать, что игнорируется, а что применяется.

Эта возможность не самая критичная. Копирования удаленного файла на целевую машину можно добиться, используя templater, не указывая переменные.

**Comment by melezhik** [comment]
давайте так - я сейчас `source`  в `file` добавлю, вы попробуете его,  а с обработкой ошибок можно чуть позже разобраться, пойдет?

**Comment by melezhik** [comment]
т.е. выкинуть сообщение о той или иной ошибке ( по входным параметрам ) -  не проблема на самом деле, это можно сделать двумя способами:

1. на уровне sparrowdo сценария - тогда это будет в чистом виде Perl6 Exception, котроый вы кстати поймаете еще ДО запуска плагинов на удаленном сервере ( что может даже предпочтительнее )

2. на уровне плагина - тогда это уже будет ВО ВРЕМЯ выполнения плагина на удаленном сервере.

Что вам подходит? Давайте решим. Я наверное больше за первый вариант.

**Comment by spigell** [comment]
Мне кажется, маловероятно, что кто-то будет копировать файлик в рамках одной системы, используя этот плагин. Поэтому лучше первый вариант.

> давайте так - я сейчас source в file добавлю, вы попробуете его, а с обработкой ошибок можно чуть позже разобраться, пойдет?

Да. конечно, давайте.

**Comment by melezhik** [comment]
готово в версии 0.0.4
```
plugin file version 0.000004 upload OK
```

**Comment by melezhik** [comment]
добавил продержку в sparrowdo - https://github.com/melezhik/sparrowdo/commit/9032ba132461b579e493bda63a0de09daeff4a26

Пример использования - https://github.com/melezhik/sparrowdo/blob/master/examples/files/sparrowfile#L25-L31

**Comment by spigell** [comment]
Да, работает.
```
'/home/spigell/test.conf' -> '/home/spigell/test.conf1'
copy source to target
target created
set target mode to 644
ok      scenario succeeded
ok      text match /target (created|deleted)/
STATUS  SUCCEED
```
А возможно ли сделать поддержку копирования файла с удаленного сервера на целевой via sparrowDO?

**Comment by melezhik** [comment]
я смотрю появился первый активный пользователь sparrow :) ,,, так насчет копирования с удаленного сервера дайте подумать ... а какой вы хотите протокол использовать для копирования? scp? ftp ?

**Comment by spigell** [comment]
Я собираюсь пользоваться sparrow и sparrowDO для домашней сети. Мне не хочется ставить ansible, chef или puppet для этого на хостах, особенно на windows (туда проще впихнуть perl, мне думается, чем все зависимости для CM). 
Давайте по ssh/scp.

**Comment by melezhik** [comment]
ок, понял. 

>  особенно на windows 

тут хочу сразу сказать, что сейчас поддержки windows нет. т.е. чисто технически ее добавить не сложно (Perl он и в африке Perl ), просто я не очень понимаю как винду с башем подружить ? Там сейчас я насколько понимаю Poweshell во всю ?

**Comment by spigell** [comment]
В win 10 уже есть баш. Также всегда есть cygwin для того, чтобы поставить sshd и perl

**Comment by melezhik** [comment]
ок, скажу сразу, я под винду sparrow не тестировал , так что там могут быть накладки, но я думаю, они все большей степени решаемые ... там как минимум еще нужен будет `curl`  ( он используется как простой http клиент для получения индекса плгинов от sparrowhub )- но, если поставить curl проблематично на винду, то можно будет заменить его каким-нибудь "легким" CPAN модулем типа `HTTP::Tiny`

**Comment by melezhik** [comment]
>  Давайте по ssh/scp.

вы хотите доступ по открытым  ключам?

**Comment by melezhik** [comment]
и еще такой вопрос - файлы для копирования будут лежать где? варианты:

* на той же машине, что и установлен sparrowdo ( ака master host ) - тогда вопрос с доступом на целевой сервер у нас уже решен
* на какой-то третей машине ( машинах ) - тогда нам нужно будет каким-то образом с этих машины на целевую ключи пробрасывать ... ( через Sparrow? )

**Comment by spigell** [comment]
> вы хотите доступ по открытым ключам?

Было бы неплохо. Смысл ключей, насколько, я понял, только в том, чтобы 10 раз не набирать пароль. И без ключа sparrow работает.

> и еще такой вопрос - файлы для копирования будут лежать где?

У меня они будут лежать на машине со SparrowDO.
Также, у моего пользователя будут все необходимые ключи.

**Comment by melezhik** [comment]
Ок, да смысл ключей как раз в том чтобы не вводить пароль.

**Comment by melezhik** [comment]
Я тут подумал, я бы не хотел добавлять копирование файлов по scp в плагин file, что бы его не перегружать. Мне кажется это лучше делать либо отдельным плагином или плагинами ( один для проброса ключей , другой собственно для копирования ). 

Либо второй вариант - реализовать все уже существующими плагинами, функциями Sparrowdo. Для создания ключа можно использовать функцию template, для вызова команд scp функцию bash. Примеры вызовов данных функций можно увидеть здесь -  https://github.com/melezhik/sparrowdo/blob/master/core-dsl.md#templates . 

Скажите, что вы думаете?

**Comment by melezhik** [comment]
То есть как вариант можно сначала попробовать все сделать через существующие плагины - templater, file, bash - не думаю, что это будет сильно сложно.  А потом,  в случае необходимости, написать для копирования удаленных файлов отдельные плагины.

**Comment by spigell** [comment]
Да, действительно, про функции в sparrowdo я просмотрел. С ними должно все получиться.
Этот кейс можно закрыть, я думаю.
Спасибо.

**Comment by melezhik** [comment]
да, на самом деле функции sparrowdo (core-dsl так называемый ) не что инное как высокоуровневые обертки для вызовов плагинов, но они есть не для всех плагинов, но всегда можно вызывать плагин напрямую ( так называемый plugin API, через функцию `task-run(...)`). Вобщем, если будут сложности - пишите, чем смогу - помогу :)

да и спасибо, что решили попробовать sparrowdo! :)

**Comment by melezhik** [comment]
@Spigell я добавил недавно функцию scp в sparrowdo core-dsl , она пока не задокументирована, вот пример вызова:


    scp %( 
      data    => "/your/local/file1 /your/local/file2"
      host    => "192.168.0.1:/path/at/remote/host", 
      user    => $ssh-user, 
      ssh-key => $ssh-private-key, 
      create  => "/tmp/do/not/copy/twice"
    );

data - задаёт  пути ( в формате утилиты scp )  для копирования файлов с целевового севера на сервер, заданный параметром host ( в формате утилиты scp ) . 

Возможно вам будет полезно.  Что бы функция была доступна -  Зачекаутите последние коммиты Sparrowdo

**Comment by melezhik** [comment]
@Spigell  для информации - http://sparrowdo.wordpress.com/2017/02/01/sshscp-commands-with-sparrowdo/ … - an informal explanation of #Sparrowdo ssh/scp code-dsl functions

**Comment by spigell** [comment]
Хм, интересно, да. Хорошо, что ключ сам делает и удаляет после окончания. Но мне не приходит в голову случай, когда такое пригодится, то есть схема SparrowDO(master) -> sparrow(client) -> remotehost мне непонятна. Это очень похоже на экспортированные ресурсы паппета, где ноды могут обмениваться между собой информацией. Но все равно класно получилось. 

Возможно, было бы еще лучше, если бы, скажем, в scp функции можно было не только пушить файлы от себя, но и забирать с мастер-хоста. Как я понял из коммитов scp/ssh это обертка над file и bash плагинами, то есть то, что выше обговаривали. Может стоит добавить параметр `action` и в зависимости от него либо пушить, либо забирать файлы откуда-нибудь. 
Просто дело в том, что функция slurp рабоает только с текстом UTF-8 и на какую-нибудь картинку выдает:
```
Malformed UTF-8
  in block <unit> at EVAL_0 line 2
  in sub MAIN at /home/spigell/.perl6/resources/CBD5665FDF294D635A231F760630B5EAAFCAD8C1 line 72
  in block <unit> at /home/spigell/.perl6/resources/CBD5665FDF294D635A231F760630B5EAAFCAD8C1 line 170

```
А пример с file как раз использует эту функцию. А вдруг мне приспичет какую-нибудь бинарщину перекидать на хосты.

**Comment by melezhik** [comment]
> Возможно, было бы еще лучше, если бы, скажем, в scp функции можно было не только пушить файлы от себя, но и забирать с мастер-хоста 

уже есть :), воспользуйтесь ключом `pull` - https://github.com/melezhik/sparrowdo/blob/master/core-dsl.md#scp

**Comment by melezhik** [comment]
>  Как я понял из коммитов scp/ssh это обертка над file и bash плагинами, то есть то, что выше обговаривали

Да, совершенно верно. Это хороший пример как лекго добавлять в sparrowdo требуемую фунциональность , просто базируясь на прмитивах - sparrow плагинах

**Comment by melezhik** [comment]
> Просто дело в том, что функция slurp рабоает только с текстом UTF-8 и на какую-нибудь картинку выдает: ... А пример с file как раз использует эту функцию. А вдруг мне приспичет какую-нибудь бинарщину перекидать на хосты.

Сейчас с `scp %( pull => 1)` это уже не проблема , юзаем scp/ssh (: . `file` - для простых случаев.

**Comment by melezhik** [comment]
> Хм, интересно, да. Хорошо, что ключ сам делает и удаляет после окончания. Но мне не приходит в голову случай, когда такое пригодится, то есть схема SparrowDO(master) -> sparrow(client) -> remotehost мне непонятна. Это очень похоже на экспортированные ресурсы паппета, где ноды могут обмениваться между собой информацией. Но все равно класно получилось.

Спасибо. История такая. Мне по работе нужно было _быстро_ доставить нетривиальные обновления на примерно 500  серверов. Мы обновляли шеф клиенты на них , плюс еще конфиги меняли. Короче достаточно критичная задача и непростая в реализации. По идеологичяеским причинам - мне на эти серверы sparrow ставить нельзя. Вот и пришлось выкручиваться - поднял около 10 вспомогательных серверов - воркеров, настроил их через saprrowdo сценарий ( на сами вокреры sparrow можно было статвить разумеется  ) - и с них просто "раздавал" по ssh обновления на все 600 серверов в 10 потоков. Уложился за пару часов. Такой получился интересный кейс. Короче sparrowdo -> target host -> (ssh/scp) -> remote host - когда у вас нет возможности ставить sparrow на remote host, но при этом вы хотите как-то его настроить. Target host выступает как посредник - на него можно складывать готовые конфиги или файлы ( через `template` или `file` ) для дальнейшего банального коипвания на remote-host по scp. Как оказывается очень полезно ... по крайне мере в моем случае ...

**Comment by spigell** [comment]
> я добавил недавно функцию scp в sparrowdo core-dsl , она пока не задокументирована, вот пример вызова:

Хм, а вот тут у меня произошла загвозка. Я только сейчас выкачал git репу sparrowDO и установил через panda:
```
[spigell@dev1 ~]$ ~/.perl6/bin/panda info ./sparrowdo/
Sparrowdo (version 0.0.7 available, 0.0.7 installed)
Configuration management tool based on sparrow plugins system
Depends on: Terminal::ANSIColor, JSON::Tiny
State: installed
Source-type: git
Perl: 6.*
Support: bugtracker     https://github.com/melezhik/sparrowdo/issues
source  https://github.com/melezhik/sparrowdo.git
Source-url: ./sparrowdo/
Provides: Sparrowdo     lib/Sparrowdo.pm6
Sparrowdo::Core::DSL::Bash      lib/Sparrowdo/Core/DSL/Bash.pm6
Sparrowdo::Core::DSL::CPAN::Package     lib/Sparrowdo/Core/DSL/CPAN/Package.pm6
Sparrowdo::Core::DSL::Directory lib/Sparrowdo/Core/DSL/Directory.pm6
Sparrowdo::Core::DSL::File      lib/Sparrowdo/Core/DSL/File.pm6
Sparrowdo::Core::DSL::Group     lib/Sparrowdo/Core/DSL/Group.pm6
Sparrowdo::Core::DSL::Package   lib/Sparrowdo/Core/DSL/Package.pm6
Sparrowdo::Core::DSL::Service   lib/Sparrowdo/Core/DSL/Service.pm6
Sparrowdo::Core::DSL::Ssh       lib/Sparrowdo/Core/DSL/Ssh.pm6
Sparrowdo::Core::DSL::Template  lib/Sparrowdo/Core/DSL/Template.pm6
Sparrowdo::Core::DSL::User      lib/Sparrowdo/Core/DSL/User.pm6
Authors: Alexey Melezhik
```
При этом такое чувство, что что-то не работает
```
[spigell@dev1 ~]$ ~/.perl6/bin/sparrowdo --host=127.0.0.1 --verbose --sparrowfile=sparrowfiles/sparrowfile-test
running sparrow tasks on 127.0.0.1 ... 
ssh -o ConnectionAttempts=1  -o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -tt -p 22 127.0.0.1 "sudo bash -c 'export LC_ALL=en_US.UTF-8 ; export GIT_PROTOCOL=https ; export PATH=/sbin/:/usr/local/bin:/usr/sbin/:$PATH ; export SPARROW_ROOT=/opt/sparrow ; echo print os | perl -MOutthentic  > /tmp/os.txt'"
Warning: Permanently added '127.0.0.1' (ECDSA) to the list of known hosts.
spigell@127.0.0.1's password: 
Connection to 127.0.0.1 closed.
scp -o ConnectionAttempts=1 -o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  -P 22 127.0.0.1:/tmp/os.txt /tmp/target_os
Warning: Permanently added '127.0.0.1' (ECDSA) to the list of known hosts.
spigell@127.0.0.1's password: 
Permission denied, please try again.
spigell@127.0.0.1's password: 
os.txt                                                                                                                                                          100%    7     0.0KB/s   00:00    
target OS is - centos7
Too few positionals passed; expected 2 or 3 arguments but got 1
  in sub scp at /home/spigell/.perl6/resources/CBD5665FDF294D635A231F760630B5EAAFCAD8C1 line 144
  in block <unit> at EVAL_0 line 1
  in sub MAIN at /home/spigell/.perl6/resources/CBD5665FDF294D635A231F760630B5EAAFCAD8C1 line 72
  in block <unit> at /home/spigell/.perl6/resources/CBD5665FDF294D635A231F760630B5EAAFCAD8C1 line 170

```

сам sparrowfile file
```
[spigell@dev1 ~]$ cat ./sparrowfiles/sparrowfile-test
scp %( 
  data    => "dir-test/",
  host    => "127.0.0.1:/home/spigell/sparrowfile", 
  user    => "spigell",
  pull    => 1, 
);
[spigell@dev1 ~]$ 
```
Можете подсказать, в чем примерно проблема может быть. 
На функцию ssh тоже выдает
```
===SORRY!=== Error while compiling /home/spigell/EVAL_1
Undeclared routine:
    ssh used at line 3

```

Я думаю, что дело в том, что чего-то не хватает (другие функции работают). Но ставил я прямо из этого каталога, выкаченного с этой репы.

**Comment by melezhik** [comment]
Это бага текущей версии Perl6, нужно удалить модуль Sparrowdo и поставить заново. Я делаю это зефом: 

    $ panda install zef 
    $ zef uninstall .
    $ zef install .

**Comment by spigell** [comment]
Здравствуйте. Вроде помогло, спасибо.
